name: fnapp

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - lib/**
      - fnapp/**
      - fnapp.Tests/**

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./fnapp
      - name: Build
        run: dotnet build --no-restore -c Release
        working-directory: ./fnapp
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./fnapp.Tests
      - name: Publish
        working-directory: ./fnapp
        run: dotnet publish --no-build -c Release -o ./fnapp-build
      - name: deploy fnapp
        uses: Azure/functions-action@v1.5.2
        with:
          app-name: fnapp
          package: ./fnapp/fnapp-build
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
