name: fnapp

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - lib/**
      - fnapp/**
      - fnapp.Tests/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./fnapp
      - name: Build
        run: dotnet build --no-restore -c Release -o fnapp-build
        working-directory: ./fnapp
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./fnapp.Tests
      - uses: actions/upload-artifact@v4
        with:
          name: fnapp
          path: ./fnapp/fnapp-build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: fnapp
      - name: deploy fnapp
        uses: Azure/functions-action@v1.5.2
        with:
          app-name: fnapp
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
