name: fnapp

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: 
      - lib/**
      - fnapp/**
      - fnapp.Tests/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./fnapp
    - name: Build
      run: dotnet build --no-restore -c Release -o fnapp-build
      working-directory: ./fnapp
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./fnapp.Tests
    - name: deploy fnapp
      uses: Azure/functions-action@v1.3.2
      with:
        app-name: fnapp-ldam
        package: fnapp-build
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}



      
